# Generated by Django 5.0.6 on 2024-05-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField()),
                ('narrative', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_code', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
