# Generated by Django 5.0.6 on 2024-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='till_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
