# Generated by Django 5.0.6 on 2024-05-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
