# Generated by Django 5.0.6 on 2024-05-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_file_alter_customers_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
